version: '3'

services:
    app:
        image: c-rest:latest
        container_name: c-rest-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:8080"
        tty: true